apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-exporter.fullname" . }}
  labels:
    {{- include "cloudflare-exporter.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.addPrometheusScrapeAnnotation }}
    prometheus.io/scrape: "true"
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudflare-exporter.selectorLabels" . | nindent 4 }}
