apiVersion: v2
name: cloudflare-exporter
version: 0.1.0
appVersion: 0.0.2
home: https://github.com/lablabs/cloudflare-exporter
description: A Helm chart for cloudflare exporter
icon: https://www.cloudflare.com/img/logo-web-badges/cf-logo-on-white-bg.svg
keywords:
  - prometheus
  - cloudflare
  - monitoring
sources:
  - https://github.com/lablabs/cloudflare-exporter
maintainers:
  - name: martinhaus
  - name: haad
engine: gotpl
type: application
annotations:
  artifacthub.io/changes: |
    - Initial helm chart changelog
